# Generated by Django 5.0.8 on 2026-07-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('FINANCE', 'Finance Admin'), ('SUPPORT', 'Support'), ('SUPER_ADMIN', 'Super Admin')], default='USER', max_length=20),
        ),
    ]
