# Generated by Django 5.0.8 on 2026-07-05 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposittransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='gateway',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='gateway_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='reference',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='wallet.wallet'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['reference'], name='payments_de_referen_23f7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['gateway_reference'], name='payments_de_gateway_f651e0_idx'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['status'], name='payments_de_status_df9e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['created_at'], name='payments_de_created_f4c045_idx'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['user', 'status'], name='payments_de_user_id_35e4de_idx'),
        ),
    ]
