# Generated by Django 5.0.8 on 2026-08-06 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goalfunding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer')], default='CONTRIBUTOR', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='ACCEPTED', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoalShareActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('GOAL_CREATED', 'Goal Created'), ('MEMBER_INVITED', 'Member Invited'), ('MEMBER_JOINED', 'Member Joined'), ('MEMBER_DECLINED', 'Member Declined'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_LEFT', 'Member Left'), ('CONTRIBUTION', 'Contribution'), ('GOAL_COMPLETED', 'Goal Completed')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='savingsgoal',
            name='goals_savin_user_id_cffec7_idx',
        ),
        migrations.RemoveIndex(
            model_name='savingsgoal',
            name='goals_savin_user_id_af2ef5_idx',
        ),
        migrations.RenameField(
            model_name='savingsgoal',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='goalfunding',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='goal_fundings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='invite_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='require_owner_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['owner'], name='goals_savin_owner_i_33192a_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['owner', 'status'], name='goals_savin_owner_i_86d4fc_idx'),
        ),
        migrations.AddField(
            model_name='goalinvitation',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='goals.savingsgoal'),
        ),
        migrations.AddField(
            model_name='goalinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_goal_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalmember',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='goals.savingsgoal'),
        ),
        migrations.AddField(
            model_name='goalmember',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalmember',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalshareactivity',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='goals.savingsgoal'),
        ),
        migrations.AddField(
            model_name='goalshareactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_share_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='goalmember',
            unique_together={('goal', 'owner')},
        ),
    ]
